### ISSUE TITLE
Contract that doesn't appear to work

### ISSUE THREAD

**Issue by kjameslubin** [blockapps/blockapps-js#14]
```
contract addr { 
  address contractAddress;
  function getContractAddress() returns (address selfAddress){
     contractAddress = this;
     return contractAddress;
  }
}
```

**Comment by ryanreich** [comment]
Works for me.  I wonder if the problem arises from incorrect usage?  Here is how you should do it:
```js
var lib = require("blockapps-js")
var code = "contract addr { \
  address contractAddress; \
  function getContractAddress() returns (address selfAddress){ \
     contractAddress = this; \
     return contractAddress; \
  } \
}"
lib.Solidity(code).call("newContract", <private key>).then(function(contr) {
  contr.state.getContractAddress().callFrom(<private key>).then(function(addr) { <do something> });
}
```

**Comment by kjameslubin** [comment]
Maybe it's a bloc issue then. There was a weird error trace:
```
Unhandled rejection RangeError: attempt to write outside buffer bounds
    at n.write (http://hacknet.blockapps.net/static/js/api.js:8:24534)
    at i (http://hacknet.blockapps.net/static/js/api.js:1:16656)
    at u (http://hacknet.blockapps.net/static/js/api.js:1:17183)
    at i (http://hacknet.blockapps.net/static/js/api.js:11:12644)
    at r.a.23.r.exports.r._settlePromiseFromHandler (http://hacknet.blockapps.net/static/js/api.js:10:17826)
    at r.a.23.r.exports.r._settlePromiseAt (http://hacknet.blockapps.net/static/js/api.js:10:19100)
    at r.a.23.r.exports.r._settlePromises (http://hacknet.blockapps.net/static/js/api.js:10:20965)
    at n.a.2.n._drainQueue (http://hacknet.blockapps.net/static/js/api.js:9:15072)
    at n.a.2.n._drainQueues (http://hacknet.blockapps.net/static/js/api.js:9:15133)
    at a.2.r.drainQueues (http://hacknet.blockapps.net/static/js/api.js:9:13345)
```

**Comment by ryanreich** [comment]
Please try again.  I suspect the api.js on the server was outdated.

**Comment by ryanreich** [comment]
Okay, this turned out to be a combination of several factors involving outdated api.js, edge cases in input parsing, and type handling in ethereumjs-tx.
