### ISSUE TITLE
"nonce incorrect, got 0, expected 1"

### ISSUE THREAD

**Issue by liorsaar1** [blockapps/blockapps-js#32]
multiple transactions sent to the target address, without checking balance
```
fromPrivateKey 040cc61bcdcc1cb017435c6b613104628d900d8c19093ec2544cb132a7df4e2b
toAddress b5b6034eafa17769293c616fbe83e4c430554dc6
tx <Address > Transaction {
  gasPrice: <BN: e8d4a51000>,
  gasLimit: <BN: f4240>,
  value: <BN: 7d0>,
  data: <Buffer >,
  to: <Address > }
Unhandled rejection Error: Transaction: submitTransaction: transactionResult: Transaction failed with transaction result:
{
  "deletedStorage": "",
  "contractsDeleted": "",
  "gasUsed": "0000000000000000000000000000000000000000000000000000000000000000",
  "stateDiff": "",
  "time": 0.00011,
  "response": "",
  "blockHash": "18a09759ce88335e8cf7331f27befd86f1ee6c62ad2a324fd83d9e5d7754b708",
  "transactionHash": "2792962f392b0ee0f0d206f4e5aaa952e95cf92b2cb39d12a0f7d99009d3b469",
  "etherUsed": "0000000000000000000000000000000000000000000000000000000000000000",
  "newStorage": "",
  "message": "nonce incorrect, got 0, expected 1",
  "trace": "",
  "contractsCreated": ""
}

Transaction was:
[
  {
    "transactionType": "Transfer",
    "next": "/eth/v1.0/transaction?hash=2792962f392b0ee0f0d206f4e5aaa952e95cf92b2cb39d12a0f7d99009d3b469&index=802",
    "hash": "2792962f392b0ee0f0d206f4e5aaa952e95cf92b2cb39d12a0f7d99009d3b469",
    "gasLimit": 1000000,
    "codeOrData": "",
    "gasPrice": 1000000000000,
    "to": "b5b6034eafa17769293c616fbe83e4c430554dc6",
    "value": "1004",
    "from": "bca850c2bb7c309f5a165f241e207f43e663b1aa",
    "fromBlock": "False",
    "blockNumber": 801,
    "r": "b3568d7bd000b955bfb34f67572a1189ddd6ab82d5837c6e1be77a426124ab1c",
    "s": "9b70a6285259d2f39ef5571bba54b54af16da46a28e4f923c22405f9b94fc8c8",
    "timestamp": "2016-04-25 17:00:50.166619 UTC",
    "v": "1c",
    "nonce": 0
  }
]
    at Object.ensureErrorObject (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/promise.js:469:22)
    at Promise._settlePromiseFromHandler (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/promise.js:513:17)
    at Promise._settlePromiseAt (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Work/blockapps/strato-explorer/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by liorsaar1** [comment]
Dev error. Closing.
