### ISSUE TITLE
Blockapp compile "bloc compile SimpleStorage" throws Cannot read property ‘bin’ of undefined error

### ISSUE THREAD

**Issue by akshathahegdeA** [blockapps/blockapps-js#42]
C:\Users\blockapp-sample\bapplication>bloc compile SimpleStorage
Compiling single contract: SimpleStorage.sol
compile failed with error message: Solidity: Cannot read property ‘bin’ of undefined

**Comment by samrit** [comment]
@akshathahegdA Check your config.yaml. It should look like the following

```
appName: bapplication
developer: Name
email: emailaddress@provider.net
apiURL: 'http://strato-ms-dev.eastus.cloudapp.azure.com/strato-api'
profile: ethereum-frontier
```

**Comment by akshathahegdeA** [comment]
@samrit I tried with the above config.yaml which worked for "block compile SimpleStorage" but when I tried to upload i.e "bloc upload SimpleStorage" it shows below error.

C:\Users\blockapp-sample\bapplication>bloc upload SimpleStorage
address: 150646613ad8bfd95066ab6bccef6439e6b64fcc
prompt: Enter password to retrieve private key:
upload contract: hello_world
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
there was an error: {"errorTags":["submitTransaction","Transaction","Solidity"],"message":"waited 10 seconds"}
creating metadata for SimpleStorage
Unhandled rejection Error: {"errorTags":["submitTransaction","Transaction","Solidity"],"message":"waited 10 seconds"}
    at Object.ensureErrorObject (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\util.js:261:20)
    at Promise._rejectCallback (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:472:22)
    at Function.Promise.reject.Promise.rejected (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:199:9)
    at C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\templates\app\lib\upload.js:55:14
    at tryCatcher (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
